<a href="https://colab.research.google.com/github/tmw622/Mingwei_INFO2020_Spring2020/blob/master/lesson06/codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.array([2,3,8])
print(2.1*a)
b=[2,3,8]
print(2*b)

print(np.dot(a,a))


[ 4.2  6.3 16.8]
[2, 3, 8, 2, 3, 8]
77


In [0]:
b=np.array([[2,3,8],[4,5,6]])
print(b[1,2])
print(b[1][2])

print(b[:,1])
print(b[:][1])

6
6
[3 5]
[4 5 6]


In [0]:
a=np.array([230,10,284,39,76])
cutoff=200
print(a>cutoff)

a[a<cutoff]=0
print(a)

[ True False  True False False]
[230   0 284   0   0]


In [0]:
import numpy as np
a=np.array([[0,1],[2,3],[4,5]])
b=np.array([10,100])
print(a*b)

c=np.array([[0,1,2],[3,4,5]])
print(c*b)

[[  0 100]
 [ 20 300]
 [ 40 500]]


ValueError: ignored

In [0]:
with open("test.txt","w") as myfile:
  myfile.write("My First file written from python\n")
  myfile.write("----------------------------------\n")
  myfile.write("Hello World!\n")

In [0]:
import random
rng=random.Random()
dice_throw=rng.randrange(1,7)
delay_in_seconds=rng.random()
random_odd=rng.randrange(1,100,2)

print(dice_throw)
print(delay_in_seconds)
print(random_odd)

5
0.609507828326317
91


In [0]:
cards=list(range(52))
print(cards)
rng.shuffle(cards)
print(cards)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
[28, 22, 16, 3, 33, 50, 8, 37, 36, 4, 13, 18, 12, 42, 5, 47, 19, 23, 2, 21, 9, 32, 11, 31, 1, 7, 17, 34, 49, 30, 38, 0, 39, 48, 25, 29, 40, 51, 43, 26, 24, 41, 46, 27, 45, 44, 10, 35, 14, 6, 20, 15]


In [0]:
import time
def do_my_sum(xs):
  sum=0
  for v in xs:
    sum+=v
  return sum

sz=1000000
testdata=range(sz)

t0=time.process_time()
myresult=do_my_sum(testdata)
t1=time.process_time()

print("myresult={0} (time taken={1:.4f} seconds)".format(myresult,t1-t0))


myresult=499999500000 (time taken=0.0664 seconds)


In [0]:
def remove_at(pos,seq):
    return seq[:pos]+seq[pos+1:]

In [0]:
import urllib.request

url="http://www.baidu.com"
destination_filename="baidu.txt"
urllib.request.urlretrieve(url,destination_filename)

In [0]:
import seqtools
import module1

s="A string!"
print(seqtools.remove_at(4,s))

print(module1.question)

In [0]:
with open("files/test.txt", "w") as myfile:
  myfile.write("My First file written from python\n")
  myfile.write("----------------------------------\n")
  myfile.write("Hello World!\n")